run_testcases:
  - PerformanceDynamic_com_example_wsywechat_0010
  - ResourceUsage_PerformanceDynamic_xhs_0060
  - ResourceUsage_PerformanceDynamic_jingdong_0010
  - PerformanceDynamic_com_alipay_mobile_client_0010
  - PerformanceDynamic_com_alipay_mobile_client_0020
  - PerformanceDynamic_com_alipay_mobile_client_0060
  - PerformanceDynamic_com_alipay_mobile_client_0070
  - PerformanceDynamic_com_ss_hm_ugc_aweme_0010
