run_testcases:
#  - PerformanceDynamic_com_example_wsywechat_0010
#  - ResourceUsage_PerformanceDynamic_xhs_0010
#  - ResourceUsage_PerformanceDynamic_xhs_0020
#  - ResourceUsage_PerformanceDynamic_xhs_0030
#  - ResourceUsage_PerformanceDynamic_xhs_0040
#  - ResourceUsage_PerformanceDynamic_xhs_0050
#  - ResourceUsage_PerformanceDynamic_xhs_0060
#  - ResourceUsage_PerformanceDynamic_xhs_0070
#  - ResourceUsage_PerformanceDynamic_bilibili_0010
#  - ResourceUsage_PerformanceDynamic_bilibili_0020
#  - ResourceUsage_PerformanceDynamic_bilibili_0030
#  - ResourceUsage_PerformanceDynamic_bilibili_0040
#  - ResourceUsage_PerformanceDynamic_bilibili_0050
#  - ResourceUsage_PerformanceDynamic_jingdong_0010
#  - ResourceUsage_PerformanceDynamic_jingdong_0020
#  - ResourceUsage_PerformanceDynamic_jingdong_0030
#  - ResourceUsage_PerformanceDynamic_jingdong_0040
#  - ResourceUsage_PerformanceDynamic_jingdong_0050
#  - ResourceUsage_PerformanceDynamic_jingdong_0080
#  - ResourceUsage_PerformanceDynamic_jingdong_0090
#  - ResourceUsage_PerformanceDynamic_jingdong_1000
#  - ResourceUsage_PerformanceDynamic_jingdong_0110
#  - ResourceUsage_PerformanceDynamic_jingdong_0120
#  - ResourceUsage_PerformanceDynamic_zhifubao_0010
#  - ResourceUsage_PerformanceDynamic_zhifubao_0020
#  - ResourceUsage_PerformanceDynamic_zhifubao_0060
#  - ResourceUsage_PerformanceDynamic_zhifubao_0070
#  - ResourceUsage_PerformanceDynamic_zhifubao_0080
#  - ResourceUsage_PerformanceDynamic_zhifubao_0100
#  - ResourceUsage_PerformanceDynamic_Douyin_0010
#  - ResourceUsage_PerformanceDynamic_taobao_9999
so_dir:
  ResourceUsage_PerformanceDynamic_xxx:
    - xxx