import path from "node:path";
import type { RunState, StageId, StageResult } from "../domain.js";
import type { StageContext, WorkflowStage } from "./contracts.js";

export abstract class AgentStage implements WorkflowStage {
  abstract readonly id: StageId;
  abstract readonly title: string;
  abstract readonly documents: string[];

  protected skip(_state: RunState): string | undefined { return undefined; }
  protected abstract instruction(state: RunState): string;

  async execute(context: StageContext): Promise<StageResult> {
    const reason = this.skip(context.state);
    if (reason) return skipped(reason);
    const request = context.state.request;
    const documentPaths = ["SKILL.md", ...this.documents]
      .map((document) => path.join(context.skillRoot, document));
    return context.agent.runStage({
      runId: context.state.id,
      stage: this.id,
      title: this.title,
      request,
      authorizedRoots: [
        context.skillRoot,
        request.projectRoot,
        request.haprayRoot,
        request.reportsPath,
        request.sourceDir,
        request.soDir,
        request.repoRoot,
        request.outputDir,
      ].filter((root): root is string => Boolean(root)),
      onSession: context.onSession,
      onEvent: context.onAgentEvent,
      prompt: [
        "You are executing exactly one bounded stage of the HapRay workflow.",
        `Stage: ${this.id} (${this.title}).`,
        `Original user request: ${request.request}`,
        "The service already completed the path prompt gate. Do not ask for paths again.",
        "Read every listed document completely before running any shell command, then follow its MUST gates.",
        "Do not delegate work to subagents. Use direct, bounded read/search/SQL tools so every operation remains observable in this stage session.",
        ...documentPaths.map((document) => `- ${document}`),
        request.outputDir
          ? `Keep service state and intermediate artifacts under projectRoot. Final reports may also be written under the explicitly authorized outputDir: ${request.outputDir}.`
          : "All generated files, downloads, reports, logs, test cases, and contracts must stay under projectRoot.",
        request.haprayRoot
          ? `Use the validated HapRay tool root for tool discovery and execution: ${request.haprayRoot}. Do not substitute an implicit home-directory installation.`
          : "This existing-report run has no HapRay tool root; analyze the supplied report inputs without setup or collection.",
        "The user requires a from-scratch analysis. Never read or reuse pre-existing agent-authored reports, including old root_cause.md, hapray-analysis-*.md, .hapray/evidence/*, or prior .hapray-service runs. Raw profiler JSON/DB/trace/HTML inputs are allowed. Reports generated by this run and named in completed upstream stage results may be consumed by downstream stages.",
        "Do not execute work belonging to a later pipeline stage. Do execute this stage fully, including its deterministic HapRay CLI commands and verification.",
        this.instruction(context.state),
        `Validated request and paths:\n${JSON.stringify(request, null, 2)}`,
        `Completed upstream stage results:\n${JSON.stringify(upstreamResults(context.state, this.id), null, 2)}`,
        "In the structured result, list only files or directories produced or updated by this stage as artifacts. Never list commands, device identifiers, Skill documents/scripts, sourceDir, or soDir inputs as artifacts. Report newly proven performance bugs and root causes as findings; do not report speculation as fact. Artifact paths must be absolute and inside projectRoot or the explicitly authorized outputDir.",
        ...(this.id === "setup" && request.haprayRoot
          ? [`Setup-stage tool artifacts may also be reported from the explicitly authorized haprayRoot: ${request.haprayRoot}.`]
          : []),
        ...(this.id === "setup" && request.repoRoot
          ? [`Setup-stage build artifacts may also be reported from the explicitly authorized repoRoot: ${request.repoRoot}.`]
          : []),
        "Do not report input files or files outside the authorized artifact roots as artifacts.",
      ].join("\n\n"),
    });
  }
}

function skipped(reason: string): StageResult {
  return { status: "skipped", summary: reason, decision: reason, artifacts: [], findings: [], data: {} };
}

function upstreamResults(state: RunState, current: StageId): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const stage of state.stages) {
    if (stage.id === current) break;
    if (stage.result) result[stage.id] = stage.result;
  }
  return result;
}
