# 测试配置参数
test_settings:
  
  # 应用相关
  app_package: "com.example.wsywechat"  # 被测应用的包名
  app_name: "mini wechat"  # 被测应用的显示名称
  scene: "wechat002"  # 测试场景
  
  # 工具路径
  trace_streamer: "D:/chromeDownload/trace_streamer_binary/trace_streamer_binary/trace_streamer_window.exe"  # trace_streamer工具路径

    # 性能采样相关
  duration: 30  # 默认采样时长（秒）
  output_path: "/data/local/tmp/perf.data"  # 性能数据在手机中的输出路径
  output_dir: "pref_output"  # 本地输出根目录
  data_filename: "perf.data"  # 性能数据文件名
  db_filename: "perf.db"  # 数据库文件名

  # 测试步骤配置
  steps:
    - name: "step1"
      description: "执行与丁真的聊天操作，发送多条消息并返回"
    - name: "step2"
      description: "执行扫一扫和收付款操作，发送告别消息并返回"
    - name: "step3"
      description: "执行发现和联系人操作，发送位置信息并滑动"