"""
prompts.py

LLM 提示词。支持两种模式：
  - polish      : 传统润色模式，把确定性草稿整理成 fixer-oriented Markdown（旧行为，向下兼容）
  - code_review : 代码审查模式，LLM 阅读反编译代码片段 + 调用链，输出结构化 JSON 根因报告（新）
"""

from __future__ import annotations

import json
from typing import Any

from .structured_output import OUTPUT_SCHEMA_STR


# ── 润色模式（保留，向下兼容）──────────────────────────────────────────────

EMPTY_FRAME_SYSTEM_PROMPT_ZH = """你是一名 HarmonyOS / ArkUI 空刷根因分析助手。

你会收到三类输入：
1. 性能上下文摘要
2. 结构化证据 JSON
3. 一份已经由规则生成的确定性 Markdown 草稿

你的职责不是重新发明结论，而是把它整理成更适合修复者阅读的最终报告。

## 强约束
- 必须保留草稿里的关键数字、线程名、候选页面/组件/方法、文件与行号范围。
- 如果草稿中已经给出了 `/proc` 用户态源码嫌疑列表，必须保留其排序和文件/行号，不要展开成长篇分析。
- 候选代码范围只能表述为 likely / candidate / 优先排查范围，不能说成"已确认根因"。
- 建议必须和证据、页面、组件、生命周期入口或 `/proc` 命中的源码入口相关。
- 如果证据不足，必须明确写在 Caveats 里。

## 输出格式
直接输出 Markdown，优先保持短版 fixer-oriented 结构：
- Executive Summary
- Detection Snapshot
- Top Suspects
- Fix Checklist
- Caveats
- Appendix: Top Evidence

面向 fixers 写作：优先给出最值得先看的 3~5 个 suspect source，并说明它为什么可疑。"""

EMPTY_FRAME_SYSTEM_PROMPT_EN = """You are a HarmonyOS / ArkUI empty-frame root-cause analysis assistant.

You will receive:
1. summarized performance context
2. structured evidence JSON
3. a deterministic markdown draft generated by rules

Your job is to refine the draft for engineers who will fix the issue.
Preserve all concrete facts, file paths, line ranges, and the ordering of any `/proc` user-space suspect list already present.
Do not turn a compact suspect list into a long narrative.
Keep candidate scopes explicitly tentative.
Output concise markdown in this structure:
- Executive Summary
- Detection Snapshot
- Top Suspects
- Fix Checklist
- Caveats
- Appendix: Top Evidence
"""

GENERAL_SYSTEM_PROMPT_ZH = "你是一名专业的 HarmonyOS 应用性能分析专家，输出面向修复者的根因分析报告。"
GENERAL_SYSTEM_PROMPT_EN = "You are a professional HarmonyOS performance analysis expert producing fixer-oriented root cause reports."


# ── 代码审查模式（新）─────────────────────────────────────────────────────

_CODE_REVIEW_SYSTEM_PROMPT_ZH = """你是一名 HarmonyOS / ArkUI 性能专家，专精空刷（empty frame）根因分析。

## 你的任务
阅读提供的「反编译代码片段」和「调用链路」，结合性能证据，输出结构化 JSON 根因报告。

## 分析要点
1. **代码审查**：重点检查以下模式（常见空刷根因）：
   - `aboutToAppear` / 生命周期方法里无 diff 的状态重赋值（每次都 `this.xxx = newVal`）
   - `setInterval` / `requestAnimationFrame` / VSync 回调里无条件触发 UI 更新
   - `ForEach` / `LazyForEach` 数据源引用变化（对象重建而非原地修改）
   - 父组件状态变化导致子组件整段重建（无 `@Reusable` 或无 key 隔离）
   - JS Bridge 回调在页面静止时仍持续写状态
2. **调用链路**：确认触发路径是否合理（VSync → JS → ArkUI → 嫌疑函数）
3. **置信度判断**：
   - `high`：代码中明确存在问题模式 + 调用链命中
   - `medium`：代码有嫌疑但需人工确认 / 调用链不完整
   - `low`：仅靠名字关联，未见明确问题代码

## 强约束
- 只分析提供的代码片段，不得编造未出现的代码
- 修复建议必须基于代码片段中的实际代码（引用具体行或变量名）
- 如果代码片段为空或不可读，置信度设为 `low` 并在 caveats 中说明

## 输出格式
**必须输出合法 JSON**，格式如下（不要输出其他内容）：

```json
{OUTPUT_SCHEMA}
```
"""

_CODE_REVIEW_SYSTEM_PROMPT_EN = """You are a HarmonyOS / ArkUI performance expert specializing in empty-frame root cause analysis.

## Your Task
Read the provided decompiled code snippets and call chains, combine them with performance evidence,
and output a structured JSON root cause report.

## Analysis Focus
Look for these common empty-frame root causes:
- Unconditional state re-assignment in lifecycle methods (no diff check)
- setInterval / requestAnimationFrame callbacks that trigger UI updates unconditionally
- ForEach / LazyForEach data source reference changes causing full rebuild
- Parent state changes causing child component full reconstruction
- JS Bridge callbacks writing state even when page is visually idle

## Output Format
Output valid JSON only, matching this schema:

```json
{OUTPUT_SCHEMA}
```
"""


def _code_review_system_prompt(language: str, domain_knowledge: str = "") -> str:
    base = _CODE_REVIEW_SYSTEM_PROMPT_ZH if language == "zh" else _CODE_REVIEW_SYSTEM_PROMPT_EN
    base = base.replace("{OUTPUT_SCHEMA}", OUTPUT_SCHEMA_STR)
    if domain_knowledge and domain_knowledge.strip():
        section_title = "## 领域先验知识\n\n以下是人工积累的分析经验，请在审查代码时参考：\n\n"
        base = base.rstrip() + "\n\n" + section_title + domain_knowledge.strip() + "\n"
    return base


# ── 公共接口 ──────────────────────────────────────────────────────────────

def get_system_prompt(
    language: str = "zh",
    checker: str = "general",
    mode: str = "polish",
    domain_knowledge: str = "",
) -> str:
    """
    Parameters
    ----------
    mode : "polish" | "code_review"
        - polish      : 传统润色模式，输出 Markdown
        - code_review : 新代码审查模式，输出结构化 JSON
    domain_knowledge : str
        从 knowledge/ 目录加载的先验知识文本，注入 system prompt。
        仅 code_review 模式使用。
    """
    if mode == "code_review":
        return _code_review_system_prompt(language, domain_knowledge=domain_knowledge)
    if checker == "empty-frame":
        return EMPTY_FRAME_SYSTEM_PROMPT_ZH if language == "zh" else EMPTY_FRAME_SYSTEM_PROMPT_EN
    return GENERAL_SYSTEM_PROMPT_ZH if language == "zh" else GENERAL_SYSTEM_PROMPT_EN


def build_user_prompt(
    context_text: str,
    extra_context: str = "",
    checker: str = "general",
    draft_report: str = "",
    structured_evidence: dict[str, Any] | None = None,
    # 代码审查模式新增字段
    code_snippets: list[dict[str, Any]] | None = None,
    call_chains_text: str = "",
    mode: str = "polish",
) -> str:
    """
    构建 user prompt。

    mode="polish"      : 传统模式，输入草稿 + 证据 JSON
    mode="code_review" : 代码审查模式，输入代码片段 + 调用链 + 精简证据
    """
    if mode == "code_review":
        return _build_code_review_user_prompt(
            context_text=context_text,
            code_snippets=code_snippets or [],
            call_chains_text=call_chains_text,
            structured_evidence=structured_evidence,
        )

    # ── 传统润色模式（向下兼容）──────────────────────────────────────
    parts: list[str] = []
    if checker == "empty-frame":
        parts.append(
            "请基于以下输入生成最终的空刷嫌疑报告。"
            "优先保留确定性草稿中的 Top Suspects、`/proc` 用户态源码文件与行号、Fix Checklist，"
            "不要扩写成冗长报告。"
        )
    else:
        parts.append("请基于以下输入生成最终根因分析报告。")

    parts.append("\n## 性能上下文\n")
    parts.append(context_text)

    if structured_evidence:
        parts.append("\n## 结构化证据(JSON)\n")
        parts.append("```json")
        parts.append(json.dumps(structured_evidence, ensure_ascii=False, indent=2))
        parts.append("```")

    if draft_report:
        parts.append("\n## 确定性草稿\n")
        parts.append("```markdown")
        parts.append(draft_report)
        parts.append("```")

    if extra_context:
        parts.append(f"\n## 补充信息\n{extra_context}\n")

    return "\n".join(parts).strip() + "\n"


def _build_code_review_user_prompt(
    context_text: str,
    code_snippets: list[dict[str, Any]],
    call_chains_text: str,
    structured_evidence: dict[str, Any] | None,
) -> str:
    """代码审查模式的 user prompt 构建。"""
    parts: list[str] = []
    parts.append("请分析以下空刷性能问题，输出结构化 JSON 根因报告。\n")

    parts.append("## 性能摘要\n")
    parts.append(context_text)

    # 精简证据摘要（只取最关键字段，减少 token 噪声）
    if structured_evidence:
        overview = structured_evidence.get("overview", {})
        dominant = structured_evidence.get("dominant_threads", [])[:3]
        frames = structured_evidence.get("representative_frames", [])[:1]
        compact: dict[str, Any] = {
            "empty_frames": overview.get("total_empty_frames"),
            "empty_rate": overview.get("empty_frame_percentage"),
            "severity": overview.get("severity_level"),
            "main_thread_pct": overview.get("main_thread_percentage_in_empty_frame"),
            "top_threads": [t.get("thread_name") for t in dominant],
        }
        if frames:
            compact["top_frame_wakeup"] = [
                w.get("thread_name")
                for w in (frames[0].get("wakeup_threads") or [])[:4]
            ]
            compact["top_frame_symbols"] = frames[0].get("symbol_hints", [])[:4]
        parts.append("\n## 关键证据\n")
        parts.append("```json")
        parts.append(json.dumps(compact, ensure_ascii=False, indent=2))
        parts.append("```")

    # 调用链路
    if call_chains_text and call_chains_text.strip():
        parts.append("\n## 触发调用链路\n")
        parts.append(call_chains_text)

    # 代码片段（核心输入）
    if code_snippets:
        parts.append("\n## 反编译代码片段\n")
        parts.append("以下是与空刷代表帧最相关的嫌疑代码片段（由反编译工具自动提取）：\n")
        for i, item in enumerate(code_snippets[:5], 1):
            owner = item.get("owner_name", "unknown")
            symbol = item.get("symbol_name", "unknown")
            file_name = item.get("file", "unknown")
            line_start = item.get("line_start", 0)
            line_end = item.get("line_end", 0)
            snippet = item.get("code_snippet") or ""
            evidence_hits = item.get("evidence_hits", 0)
            confidence_hint = item.get("confidence_hint", "")

            parts.append(f"### 片段 {i}: {owner}.{symbol}")
            parts.append(f"- 文件: `{file_name}:{line_start}-{line_end}`")
            if evidence_hits:
                parts.append(f"- 证据命中次数: {evidence_hits}")
            if confidence_hint:
                parts.append(f"- 预置置信度提示: {confidence_hint}")
            if snippet:
                parts.append("```typescript")
                parts.append(snippet)
                parts.append("```")
            else:
                parts.append("（代码片段不可用）")
            parts.append("")

    parts.append("\n请输出 JSON 根因报告，不要输出其他内容。")
    return "\n".join(parts).strip() + "\n"
