name: Npm build
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: euleros-2.10.1
    steps:
      - uses: checkout-action@0.0.1
      - name: Use Node.js
        uses: setup-node@0.0.1
        with:
          node-version: '20.10.0'
      - name: Set up static Python
        uses: actions/setup-python@0.0.1
        with:
          python-version: '3.11'
      - run: |
          pip config set global.index-url https://mirrors.aliyun.com/pypi/simple
          pip config set install.trusted-host mirrors.aliyun.com
          npm config set registry https://registry.npmmirror.com/
          cd repo_workspace && npm install
      - run: cd repo_workspace && npm run build
      - run: cd repo_workspace && npm run lint