# 测试配置参数
test_settings:
  
  # 应用相关
  # 微信应用配置
  app_package: "com.example.wsywechat"  # 被测应用的包名
  app_name: "mini wechat"  # 被测应用的显示名称

  # 支付宝应用配置（已注释）
  # app_package: "com.alipay.mobile.client"  # 被测应用的包名
  # app_name: "alipay"  # 被测应用的显示名称
  # scene: "ResourceUsage_PerformanceDynamic_zhifubao0030"  # 测试场景

  # 测试类型
  test_type: "default"  # 可选值: "default", "custom", "alipay" 等
  
  # 工具路径
  trace_streamer: "D:/chromeDownload/trace_streamer_binary/trace_streamer_binary/trace_streamer_window.exe"  # trace_streamer工具路径

  # 性能采样相关
  duration: 30  # 默认采样时长（秒）
  output_path: "/data/local/tmp/perf.data"  # 性能数据在手机中的输出路径
  data_filename: "perf.data"  # 性能数据文件名
  db_filename: "perf.db"  # 数据库文件名

  # 测试步骤配置
  steps:
    # 注释掉原来的步骤
    # - name: "step1"
    #   description: "1. 启动支付宝"
    # - name: "step2"
    #   description: "2. 首页上滑3次"
    # - name: "step3"
    #   description: "3. 首页下滑3次"
    # - name: "step4"
    #   description: "4. 点击更多"
    # - name: "step5"
    #   description: "5. 更多上滑"
    # - name: "step6"
    #   description: "6. 更多下滑"
    # - name: "step7"
    #   description: "7. 侧滑返回首页"
    # - name: "step8"
    #   description: "8. 点击蚂蚁森林，等待10s"
    # - name: "step9"
    #   description: "9. 侧滑返回首页"
    # - name: "step10"
    #   description: "10. 返回桌面"
    
    # 添加3个新步骤用于测试default情况
    - name: "step1"
      description: "1. 启动微信"
    - name: "step2"
      description: "2. 与丁真聊天"
    - name: "step3"
      description: "3. 返回桌面"

