# 卡顿帧分析配置文件
# HapRay Performance Analysis - Frame Analysis Configuration

frame_analysis:
  # 卡顿帧优化配置
  stuttered_frames:
    # 进行深度分析的TOP N卡顿帧数量
    # 设置为0表示分析所有卡顿帧（关闭优化）
    # 建议值: 5-20，根据性能需求调整
    top_n_analysis: 10
    
    # 是否启用轻量级模式优化
    # true: 先快速收集所有卡顿帧，再深度分析TOP N
    # false: 传统模式，分析所有卡顿帧
    enable_lightweight_mode: true
    
    # 严重程度评分权重配置
    severity_scoring:
      # 卡顿等级基础分数权重
      level_weights:
        level_1: 10    # 轻微卡顿基础分
        level_2: 50    # 中度卡顿基础分
        level_3: 100   # 严重卡顿基础分
      
      # 超出帧数权重（每帧的分数）
      exceed_frames_weight: 5.0
      
      # 超出时间权重（每毫秒的分数）
      exceed_time_weight: 0.1
  
  # 空帧分析配置
  empty_frames:
    # 空帧分析是否启用
    enabled: true
    
    # 空帧分析超时时间（秒）
    timeout: 300

  # 帧负载计算配置
  frame_loads:
    # 快速帧负载分析是否启用
    fast_mode_enabled: true
    
    # 帧负载计算超时时间（秒）
    timeout: 600

# 性能优化配置
performance:
  # 数据库连接池配置
  database:
    # 连接超时时间（秒）
    connection_timeout: 30
    
    # 查询超时时间（秒）
    query_timeout: 120
  
  # 内存优化配置
  memory:
    # 是否启用内存优化模式
    optimize_memory_usage: true
    
    # 大数据库文件阈值（MB），超过此大小启用特殊处理
    large_database_threshold: 500
    
    # 超大数据库文件阈值（MB），超过此大小发出警告
    huge_database_threshold: 1000

# 日志配置
logging:
  # 是否启用详细的性能日志
  enable_performance_logs: true
  
  # 是否启用优化策略日志
  enable_optimization_logs: true
  
  # 慢查询日志阈值（秒）
  slow_query_threshold: 10.0

# 缓存配置  
cache:
  # 是否启用数据预加载
  enable_preload: false
  
  # 缓存过期时间（秒）
  expire_time: 3600
  
  # 是否在分析完成后自动清理缓存
  auto_cleanup: true

# 兼容性配置
compatibility:
  # 是否保持向后兼容API
  maintain_backward_compatibility: true
  
  # 默认分析模式（当未指定top_n_analysis时）
  # "legacy": 分析所有帧（传统模式）
  # "optimized": 使用默认TOP N优化
  default_mode: "optimized"