name: Build Executables

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.item.os }}
    runs-on: ${{ matrix.item.os }}
    strategy:
      matrix:
        item:
          # Linux
          - os: ubuntu-latest
            arch: x64
            platform: linux
            package_lock_path: .github/workflows/package-lock.json
            
          # Windows
          - os: windows-latest
            arch: x64
            platform: win32
            package_lock_path: .github/workflows/package-lock.json
            
          # macOS - ARM (Apple Silicon)
          - os: macos-14
            arch: arm64
            platform: darwin
            pyinstaller_arch: arm64
            package_lock_path: .github/workflows/package-lock.json
            
          # macOS - x86 (Intel)
          - os: macos-13
            arch: x86_64
            platform: darwin
            pyinstaller_arch: x86_64
            package_lock_path: .github/workflows/package-lock.json
        # 将 node-version 移到每个 item 中
        include:
          - node-version: 18.x
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Copy package-lock.json
      run: |
        echo "Copying ${{ matrix.item.package_lock_path }} to package-lock.json"
        cp "${{ matrix.item.package_lock_path }}" package-lock.json
        echo "File copied successfully"
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install --no-package-lock

    - name: PyInstaller build
      run: |
        npm run release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ArkAnalyzer-HapRay-${{ matrix.item.platform }}-${{ matrix.item.arch }}
        path: ArkAnalyzer-HapRay-*.tgz